plugins {
    id 'java'
    id 'application'
    id 'maven-publish'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    testImplementation libs.junit.junit
}

group = 'com.example'
version = '1.0-SNAPSHOT'
description = 'maven-example'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
}

application {
    mainClass = 'com.example.App'
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}